update toolchain because of flate2 error
posify(snbc-880np) % cargo run --example match_manufacturer
   Compiling flate2 v1.0.27
   Compiling exr v1.7.0
error[E0658]: deriving `Default` on enums is experimental
  --> /Users/don/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.27/src/gz/mod.rs:90:17
   |
90 | #[derive(Debug, Default)]
   |                 ^^^^^^^
   |
   = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)